# Generated by Django 5.2.5 on 2025-08-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='confidence',
        ),
    ]
