# Generated by Django 5.2.5 on 2025-09-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictApp', '0002_remove_predictionhistory_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionhistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Prediction History'},
        ),
        migrations.AlterModelTable(
            name='predictionhistory',
            table='prediction_history',
        ),
    ]
